name: ProJectHub
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: 2.1.4



dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/glask.png"
  linux:
    icon: "assets/images/glask.png"
  macos:
    icon: "assets/images/glask.png"
  windows:
    generate: true
    icon: "assets/images/glask.png"


flutter:
  uses-material-design: true
  assets:
    - assets/images/glask.png
